### ISSUE TITLE
Abstract the definition of Sanctuary Types

### ISSUE THREAD

**Issue by Avaq** [fluture-js/Fluture#101]
Related to #63. Now that Fluture exposes *two* types, it becomes even more of a burden for Sanctuary users to create definitions for these types.

A solution suggested by @davidchambers [here](https://github.com/plaid/async-problem/pull/31/files/0c8542b68b05cea4c10b173f42443841e3e727e7..5cec8d2effd6c6044258e7bbfcd4660b7ca9501f#r115866488):

```js
const Future = require('fluture');
const $ = require('sanctuary-def');

const {ConcurrentFutureType, FutureType} = Future.defineTypes($);
```

This allows us not to have to define `sanctuary-def` as a dependency, but it's also a bit awkward.

I gave it some thought, and I think I should create a separate package: `fluture-sanctuary`. This package will have two *peer dependencies*: `fluture` and `sanctuary-def`, both with selectors which might span multiple major versions (eg `fluture@>2.x <6.x`), as long as the definition of the type has been unchanged. Every time a new major version comes out, I will assert whether type definition has remained unchanged, and adjust the range selector to include the new major version. Once a breaking change occurs, the `fluture-sanctuary` package will *itself* be released under a new major with a new selection range.

You could then use the package as such:

```js
const {ConcurrentFutureType, FutureType} = require('fluture-sanctuary');
```

**Comment by davidchambers** [comment]
I think `fluture-types` might be a better name than `fluture-sanctuary`. /cc @JAForbes

Why would `fluture` and `sanctuary-def` be peer dependencies rather than regular dependencies?

**Comment by JAForbes** [comment]
What if`fluture-sanctuary` was a typed interface of the entire Fluture API + exporting the 2 types?

**Comment by Avaq** [comment]
> I think `fluture-types` might be a better name than `fluture-sanctuary`. -- @davidchambers 

I think `fluture-type` is too general. There are many type systems available for JavaScript by now, but run-time and before run-time.

> Why would fluture and sanctuary-def be peer dependencies rather than regular dependencies? -- @davidchambers 

So that `npm` doesn't go off and install a different version of `sanctuary-def` from the one the user is using (in case the version selectors differ). When it's a peer dependency, npm would issue a warning in that case.

> What if  `fluture-sanctuary` was a typed interface of the entire Fluture API -- @JAForbes 

I'm not sure what you mean by "typed interface". Do you mean all functions being wrapped in `sanctuary-def` definitions? That could be interesting.

**Comment by JAForbes** [comment]
> Do you mean all functions being wrapped in sanctuary-def definitions? That could be interesting.

Yep exactly that.  But maybe it'd be nice to also include the types themselves as a separate export so if that's all you're after, you could say `const {ConcurrentFutureType, FutureType} = require('fluture-sanctuary/types')` to avoid the entire library appearing in a bundle (as an example).

**Comment by Avaq** [comment]
> But maybe it'd be nice to also include the types themselves as a separate export

I think it remains the best option to have the types reside in their own library. This will allow for the finest control over managing compatible versions. The idea to have all of Fluture wrapped by Sanctuary can live in a separate library, I expect the audience for this feature to be smaller as well.

**Comment by JAForbes** [comment]
@Avaq good points!

**Comment by davidchambers** [comment]
I believe this issue has been resolved. :)

**Comment by Avaq** [comment]
I just pushed a small update to the documentation, which was the last thing to do. :)
