### ISSUE TITLE
Encase for nodeback functions

### ISSUE THREAD

**Issue by Avaq** [fluture-js/Fluture#103]
Something like:

```diff
- const readFile = (name, options) => Future.node(done => fs.readFile(name, options, done));
+ const readFile = Future.encaseN2(fs.readFile);
```

**Comment by davidchambers** [comment]
This would make <https://github.com/plaid/async-problem/blob/davidchambers/spring-clean/futures.js> even nicer than it already is!

**Comment by Avaq** [comment]
Reading that file was part of what prompted me to open this issue. I feel a bit bad for pushing [`futurize`](https://github.com/futurize/futurize) further into obsoletion<sup>..if that's a word..</sup>, but I much prefer having fixed arity functions.
