### ISSUE TITLE
tryN

### ISSUE THREAD

**Issue by jmatsushita** [fluture-js/Fluture#107]
Hi there,

Maybe a `tryN` function which catches exceptions thrown in a node callback style function would continue to harmonise the API?

Thanks!

Jun

**Comment by Avaq** [comment]
Hi Jun, I think the function you're looking for is `node()`. I believe the `encase` family is complete:

* [try](/fluture-js/Fluture#try) and [encase](/fluture-js/Fluture#encase)
* [tryP](/fluture-js/Fluture#tryp) and [encaseP](/fluture-js/Fluture#encasep)
* [node](/fluture-js/Fluture#node) and [encaseN](/fluture-js/Fluture#encasen)

**Comment by Avaq** [comment]
I'm closing the issue, because I don't think it's actionable.
