### ISSUE TITLE
Reserved words in module exports

### ISSUE THREAD

**Issue by Avaq** [fluture-js/Fluture#110]
## The observation

Fluture's source is littered with *"reserved word exports"*. Some examples:

* `export {default, default as Future} from './src/future'`<sup>[source](https://github.com/fluture-js/Fluture/blob/136d1bc92c88b4164977b37ae1bc37fa2dca7ffa/index.es.js#L1)</sup>
* `export {attemp as try} from './src/core'`<sup>[source](https://github.com/fluture-js/Fluture/blob/136d1bc92c88b4164977b37ae1bc37fa2dca7ffa/index.es.js#L7)</sup>
* `export {lastly as finally} from './dispatchers/lastly'`<sup>[source](https://github.com/fluture-js/Fluture/blob/136d1bc92c88b4164977b37ae1bc37fa2dca7ffa/src/dispatchers.js#L8)</sup>

It seems that according to [ecma262 section 15.2.3.1](https://tc39.github.io/ecma262/#sec-exports-static-semantics-early-errors), all of the above should be syntax errors:

> For each *IdentifierName* `n` in ReferencedBindings of *ExportClause*: It is a Syntax Error if StringValue of `n` is a [*ReservedWord*](https://tc39.github.io/ecma262/#prod-ReservedWord)

In the spec for *ReservedWord* we see that `default` *is* actually a reserved word (and so are `try` and `finally`, of course).

## The consequences

1. We can "fix" the `export {default}`-cases by means of code like this:

```js
import Future from './src/future'
export default Future
```

2. We can "fix" the `export {default as named}`-case by means of code like this:

```js
import tmp from './src/future'
export const Future = tmp
```

3. :warning: I do not see any lossless way to "fix" named exports of reserved words:

```js
import {attempt} from './src/core'
export const try = attempt // Parsing Error
```

Does this mean I have to resort to the following?

```js
import {attempt} from './src/core'
export default {'try': attempt}
```

This is sub-optimal: 

* It forces users to destructure an object rather than using import syntax
* It's more difficult to tree-shake

I'm hoping someone has a better idea.

## The tooling

I find it odd that none of the following parsers recognize these export statements as Syntax Errors:

* babylon
* [babylon6](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code=export%20%7B%20default%2C%20default%20as%20Future%20%7D%20from%20'.%2Ffluture'%3B)
* babylon7
* rollup
* [typescript](http://www.typescriptlang.org/play/index.html#src=export%20%7B%20default%2C%20default%20as%20Future%20%7D%20from%20'fluture'%3B)

Have I misinterpreted the specification, or are these tools doing something wrong? In the latter case, I believe I should notify the maintainers of these tools. 

/cc @rpominov @markelog

**Comment by rpominov** [comment]
Initially I've worried not that `default` is a reserved word, but rather that an export like that may not work as a `default` export.

I.e. if we did `var default = 123; export {default}`, I'm not sure that we'll be able to do `import foo from '...'; foo === 123`, but will have to do `import {default as foo} from '...'; foo === 123` instead.

This works now because most of the tools implement `default` exports literally as an export named `"default"`, not sure if they do it by spec, or it's just an implementation details...

Anyway I, by no means, an expert in this matters. Maybe there is nothing to worry about.

**Comment by markelog** [comment]
@hzoo hey-hey, what do you think, is this a genuine concern?

**Comment by bakkot** [comment]
These are all fine. Twice over, in fact:

- The error is "For each IdentifierName n in ReferencedBindings of ExportClause". Chasing `ReferencedBindings`, you can [see](https://tc39.github.io/ecma262/#sec-static-semantics-referencedbindings) it will only include the first identifier in `foo as bar`.
- The error you reference is *only* for the production `ExportDeclaration : export ExportClause ;`, i.e., it doesn't apply to `export from`.

**Comment by Avaq** [comment]
Thanks for the clarification @bakkot! :+1:
