### ISSUE TITLE
Max call stack exceeded on parallel(1, futures)

### ISSUE THREAD

**Issue by alexshuhin** [fluture-js/Fluture#130]
I expect `parallel` to be stack safe computation, but it's not. `futures` is about 9000 items length.

Is there way to calculate `futures` sequentially without using `chain` and `reduce` explicitly? What's the best practice in this case?

**Comment by Avaq** [comment]
Oh. That's an issue I didn't see coming. Of course `parallel` has to be stack safe! Since you're using `parallel(1)`, you could use a recursive pattern while I'm working on fixing this. Something like:

```js
const lotsOfFutures = [...];

(function recur([i, xs]){
  return lotsOfFutures[i].map(x => [i + 1, [xs..., x]]).chain(recur)
}([0, []]))

.fork(...)
```

**Comment by Avaq** [comment]
Does the array contain purely *synchronously* resolving Futures?

**Comment by Avaq** [comment]
Maybe you can fix it like this:

```js
const lotsOfFutures = [...];
const makeAsync = Future.after(0);

Future.parallel(1, lotsOfFutures.map(makeAsync))

.fork(...)
```

Could you try?

**Comment by alexshuhin** [comment]
@Avaq 
> Does the array contain purely synchronously resolving Futures?

No. Therefore i asked for better practice. I prefer to have API method for sequntially computation for big futures array like `Future.sequence(futures)`, but there is `parallel` method with computation length `1` thats make that i wanted.

```javascript
//Runs all Futures in sequence:
Future.parallel(1, tenFutures).fork(console.error, console.log);
//after about 200ms:
//> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

**Comment by alexshuhin** [comment]
@Avaq 
> Maybe you can fix it like this:

const lotsOfFutures = [...];
const makeAsync = Future.after(0);

Future.parallel(1, lotsOfFutures.map(makeAsync))

.fork(...)
Could you try?

Nope =(

**Comment by Avaq** [comment]
Oh, the argument to after should have been `1`. Pardon me :) So:

```js
const lotsOfFutures = [...];
const makeAsync = Future.after(1); //<--- One! ;)

Future.parallel(1, lotsOfFutures.map(makeAsync))

.fork(...)
```

**Comment by alexshuhin** [comment]
Yea, thats works, but significantly reduce performace =( about 4-5 times slower then `reduce/chain`

**Comment by Avaq** [comment]
Yeah, that's because we're waiting a few ticks at every Futures. :\
I'm still patching `parallel`, but this is one way you can avoid the issue for now.

**Comment by Avaq** [comment]
Updating to version `6.3.0` will resolve your issue, @alexshuhin. And thank you for your :star: good sir. ;)
