### ISSUE TITLE
Parallel / Both not returning all values

### ISSUE THREAD

**Issue by anthonyshull** [fluture-js/Fluture#136]
I have two futures running in parallel, I want to return the combination of the values. But, it's only returning the values of the first future. I have tried this with parallel and with both. Same result.

Fluture 6.3.0

**Comment by anthonyshull** [comment]
In fact. Even if you try to use .ap it only returns the value of the first Future:

```
Future.of(x => y => x.concat(y)
  .ap(searchTerminals(req.server.pg, searchString))
  .ap(searchRefineries(req.server.pg, searchString))
  .fork(err => rep(err), res => rep(res));
```

searchTerminals and searchRefineries are Future [] created with Future.node. Either one run individually returns the correct array. But whenever they are combined with parallel, both, or ap then only the value of the first is returned.

**Comment by Avaq** [comment]
This seems like a problem highly unlikely to be related to Fluture itself:

* `ap`, `both` and `parallel` are each handled by very different algorithms in the code
* Each of these algorithms have unit tests which contradict your findings
* I was unable to reproduce this issue myself:
    - `ap`: https://runkit.com/embed/od4c4uu3fun5
    - `both`: https://runkit.com/embed/bo9m7jwgslcj
    - `parallel`: https://runkit.com/embed/rifmz4md490c


---

Could it be one of your Futures is rejecting with the same shape of data you expect it to resolve with? Seeing as you're using the same continuation for both rejection and resolution, you would not be able to distinguish.

If this is not the case I'll need you to share some code which reproduces your issue.

**Comment by anthonyshull** [comment]
This is why I was thinking it might be a problem with Future.node.

This is searchRefineries:

```
// searchRefineries :: DB -> Future [Refinery]
exports.searchRefineries = (client, searchString) => {
  return node((done) => {
    client.query(`SELECT "locationId", "locationType" FROM locations WHERE "locationType" = 'Refinery' AND lower("locationName") LIKE \'%${searchString}%\'`,
                 (err, res) => {
                   console.log(err, res.rows);
                   done(res.rows);
                 });
```

searchTerminals is exactly the same save the query string. Then I'm calling it like so:

```
const {parallel} = require('fluture');
const {searchRefineries, searchTerminals, searchSegments} = require('./search');

exports.search = (req, rep) => {
  const {searchString} = req.query;
  parallel(2, [searchRefineries(req.server.pg, searchString), searchTerminals(req.server.pg, searchString)])
    .fork((err) => rep(err), (res) => rep(res));
};
```

When I call with a searchString that should return refineries and terminals I get these console logs:

```
null [ anonymous { locationId: 519, locationType: 'Refinery' },
  anonymous { locationId: 517, locationType: 'Refinery' },
  anonymous { locationId: 572, locationType: 'Refinery' } ]
null [ anonymous { locationId: 573, locationType: 'Terminal' },
  anonymous { locationId: 518, locationType: 'Terminal' } ]
```

null is the error. So, they are both returning values. But, in my fork only one value is coming through.

If I search for something that is a terminal only then I see this in my log, but get an empty []...which I believe means it's just taking the first value which is empty:

```
null []
null [ anonymous { locationId: 518, locationType: 'Terminal' } ]
```

**Comment by anthonyshull** [comment]
Looked at it further. When I add a setTimeout around the resolution of the first value then the values of the second Future appear. When I remove the timeout then the value of the first Future again appears. So, it looks like it's just taking the value of whatever Future resolves first.

**Comment by Avaq** [comment]
You call done(res.rows), rejecting the Future

**Comment by Avaq** [comment]
The first argument to done is the error, as node convention dictates.

**Comment by anthonyshull** [comment]
Ah, awesome. I was thinking that done was called only on success with the successful value.

**Comment by Avaq** [comment]
The use for `Future.node` is to remove the boilerplate of defining your own `(err , res) =>` function all the time. You can use `done` as a second argument to `client.query` directly. :)
