### ISSUE TITLE
monad-t

### ISSUE THREAD

**Issue by char0n** [fluture-js/Fluture#149]
Hi,

I have implemented (with some help of my colleagues) couple of transformers using monads from monet and [fluture](https://github.com/fluture-js/Fluture) libraries into the [monad-t](https://github.com/char0n/monad-t) library. Currently we have two monad transformers: `MonetEitherT` and `FlutureTMonetEither`. I would kindly appreciate your validation of my ideas implemented into these transformers and if my ideas are valid would you mind mentioning the monad-t in your README file ?

Thank you for your time

**Comment by Avaq** [comment]
Hi @char0n 

Nice to see you experimenting with Fluture. Can you tell me a little bit more about the library? After having some quick looks at it I have a few questions:

* Could you give me an introduction to which problem it solves? Maybe an example of a problem you solved with it?
* Monad Transformers as they are implemented in the various FL repo's are different: They take two type representatives (`Left.transform(Right)`) and return a constructor (and type repr) which creates instances that have the effects of both `Left` and `Right`. It seems that in `monad-t`, something like this happens on instance level, is that right?
* I'm a little worried about one of the examples in the README: `FutureTEither.of(Future.of(Either.Right(1)))` ⇒ `FlutureTMonetEither(1)`. This makes it look like the input is transformed somehow by `of`, which it shouldn't do. Could it be that the example is misleading, or is the input actually transformed?

**Comment by char0n** [comment]
Hi @Avaq,

Thanks for finding a time and looking into the lib. monad-t is still an experimental piece of code where I put my research of monad transformers that I gathered studying various explanations from scala/scalaz, mainly this [one](https://jtcwang.me/scala-monad-transformers-by-example) and modeled my API according to the code examples found in it. 

> Could you give me an introduction to which problem it solves? Maybe an example of a problem you solved with it?

I documented the problem and the possible solution in this [article](https://www.linkedin.com/pulse/monad-transformers-javascript-vladim%C3%ADr-gorej). I guess it will give you answer to you question. I had monads from various libraries (monet, fluture) and I had to make them work together.

> Monad Transformers as they are implemented in the various FL repo's are different: They take two type representatives (Left.transform(Right)) and return a constructor (and type repr) which creates instances that have the effects of both Left and Right. It seems that in monad-t, something like this happens on instance level, is that right?

Well the answer for this question is yes and no. There is a concrete type of Fluture<Either> transformer called FlutureTMonetEither. EitherTMonet is a also a concrete type repr. But instead of consuming values, their constructors consume monad instances; e.g. `FlutureTMonetEither.of(Future.of(Either.Right(1))`

>I'm a little worried about one of the examples in the README: FutureTEither.of(Future.of(Either.Right(1))) ⇒ FlutureTMonetEither(1). This makes it look like the input is transformed somehow by of, which it shouldn't do. Could it be that the example is misleading, or is the input actually transformed?

No transformations happens. My intention was to show that the resulting monad transformers acts like it has only value locked inside, although the structure is FlutureTMonetEither<Fluture<Either<Value>>>

**Comment by Avaq** [comment]
The `fantasy-land/of` method is not lawful.

```js
> FutureTEither['fantasy-land/of'](1)['fantasy-land/map'](x => x + 1).run
TypeError: this.run[map] is not a function
```

I think to fix it, it should wrap every input in this `Future(Either)` structure. I believe a big improvement to the library would be testing with https://github.com/fantasyland/fantasy-laws/pull/1

To answer your original question:

> would you mind mentioning the monad-t in your README file?

I think monad-t caters to a very specific need (the combination of Fluture and monet). I haven't come across many users with this need.

For these kinds of needs I intend to create an issue label `faq`, and link to the list of issues with the label from within the readme. You could contribute to the FAQ yourself by posting a question like *Is there an interoperability layer with monet?*, but my preference would be to let it happen naturally.

**Comment by char0n** [comment]
Thanks for your valuable input. I've created an issue on monad-t repo to process your comments. Thanks a lot again.
