### ISSUE TITLE
Consider adding a alias for `parallel(Infinity)`

### ISSUE THREAD

**Issue by leighman** [fluture-js/Fluture#155]
The only thing I find slightly tedious about fluture is having to pass a number to parallel every time I use it when mostly I don't care because I know I have a small array.
Would it be possible to add some alias for the (probably default) case where you don't care about a parallelism limit?
I realise I can do this myself but it would save an extra include 😄 
Thanks.
Love fluture ❤️

**Comment by Avaq** [comment]
I'm not keen on doing this for a few reasons:

1. Running tasks in parallel is something potentially dangerous, as it may cause memory, or some other limited resource (eg. bandwidth, cpu) to run out. One of the design philosophies behind Fluture's API is that it should try to make users think about cases they might miss using other API's. I fear that -knowing myself- users will be more likely to just reach for an `all`-function for every case, without considering the consequences of limitless parallelism. Forcing users through a slightly tedious process where they have to explicitly provide `Inifinity` for "limitless", means that they spend a moment thinking about what this means for their specific case. Personally I appreciate this when using Fluture.
2. I generally don't really like adding functions which can be created by a single composition, or partial application. In this case `all = parallel(Inifnity)`. If I were to start adding these functions, the library would blow up in surface area, which is something I try to defend against.

That said, if enough people ask for this feature I might make an exception.

**Comment by Avaq** [comment]
I notice my previous post might come off a bit too grumpy, I should add that I welcome your ideas! Thank you for your contribution and I'm happy to see you're enjoying Fluture! ;)

**Comment by Avaq** [comment]
Closing due to a month of inactivity. I will reopen this issue if I get the same question again, to collect all support for this suggestion in one place.
