### ISSUE TITLE
Failed to minify error on create react app

### ISSUE THREAD

**Issue by lolcookie** [fluture-js/Fluture#165]
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/fluture/src/internal/throw.js:5 

Read more here: http://bit.ly/2tRViJ9
```

Any ideas on how to fix this?

**Comment by Avaq** [comment]
I believe that it's related to issue #162. Can you try using `import Future from 'fluture/index.js'` (explicitly using the es5 index.js file)?

**Comment by lolcookie** [comment]
@Avaq looks like that worked, went for the more insane fix and transpiled using babel first.

**Comment by leighman** [comment]
Still getting this with 7.2.0.

```

**Comment by Avaq** [comment]
I just fixed that. Releasing as soon as builds pass: https://github.com/fluture-js/Fluture/commit/a7ec9401c808f75dee21d3fd1dfc225b562cecc6

**Comment by Avaq** [comment]
Leftover template literals (sorry) have been removed in version `7.2.1`. Try again @leighman?
