### ISSUE TITLE
Wiki Page - Argument order for setTimeout is incorrect.

### ISSUE THREAD

**Issue by peterhry** [fluture-js/Fluture#174]
https://github.com/fluture-js/Fluture/wiki/Comparison-to-Promises#practical-differences

**Comment by Avaq** [comment]
[Fixed!](https://github.com/fluture-js/Fluture/wiki/Comparison-to-Promises/_compare/88b7beaf128f9bddf1ec75385d26502295fb353f...31f8495476b103eca229d88fc84e52ac7e1e555d) Thank you for pointing out this silly mistake. :D
