### ISSUE TITLE
Behaviour of Parallel$cancel

### ISSUE THREAD

**Issue by cortopy** [fluture-js/Fluture#181]
For what I can gather from the [parallel module](https://github.com/fluture-js/Fluture/blob/master/src/parallel.js), the `Parallel$cancel`method would cancel all the Futures which haven't been resolved or rejected yet.

Is this correct?

If so, I was wondering if you would accept a commit to the main docs to say something about this. I'm just using Fluture for the first time and this could be an unnoticed killer feature.

**Comment by Avaq** [comment]
> the `Parallel$cancel`method [cancels] all the Futures which haven't been resolved or rejected yet. Is this correct?

This is correct. Anytime Fluture notices that the result of a process is no longer needed, it is automatically cancelled. Some examples:

* All currently running Futures in `Future.parallel` when one rejects, as you found :) 
* The other in a `Future.race` when the one resolves
* The other in a `race` or `both` when the one rejects

> I was wondering if you would accept a commit to the main docs to say something about this.

Sure thing!

**Comment by cortopy** [comment]
Comments submitted to docs via https://github.com/fluture-js/Fluture/pull/185
