### ISSUE TITLE
Reasonml bindings

### ISSUE THREAD

**Issue by Koleok** [fluture-js/Fluture#195]
I was thinking of writing some [reasonml](https://reasonml.github.io/) bindings for fluture since I am trying to use reason more and more in projects and fluture has become pretty central to the way I write asynchronous js _(🎉 thanks btw @Avaq @safareli)_ 

If anyone knows of existing work, or can predict major blockers for this effort feel free to drop info in this issue 👍

**Comment by Avaq** [comment]
Hi @Koleok, I've never heard of Reason before (pun not intended), but it looks nice! You probably inferred that I don't know of any prior work regarding Reason with Fluture, nor that I can foresee any roadblocks.

I'm interested to learn more about Reason through your efforts though. Keep me informed! :)

**Comment by Avaq** [comment]
I'm closing this because it is not currently actionable. Please keep me updated by posting here or in Gitter! :)

**Comment by benadamstyles** [comment]
@Koleok, I recently published https://github.com/benadamstyles/bs-fluture – hope I haven’t pre-empted any work you’ve done. Please feel free to make any suggestions or improvements!

**Comment by Koleok** [comment]
@benadamstyles Nice 👏! I had started on this last year and worked up to a point where I got a little blocked, if I have some time this week I'll dig up what i have and see if I can contribute anything from it to your version.
