### ISSUE TITLE
Issue when using bundle.js where global throws error for setImmediate

### ISSUE THREAD

**Issue by wking-io** [fluture-js/Fluture#204]
I am trying to use Fluture in Codepen and the CDN bundle.js throws the following error:

`Reference Error: global is not defined`

The instance where global is being called is on the setImmediate function here: https://github.com/fluture-js/Fluture/blob/19febe13038ea5c9d6f2cc499d7b9052a334e611/dist/bundle.js#L2499

I was able to fix this error by wrapping an IIFE that passes the global object like this:

```
var setImmediate = (function(global) {
  return typeof global.setImmediate === 'function'
  ? global.setImmediate
  : /* istanbul ignore next: environment-specific */ setImmediate$1;
})(/*istanbul ignore next*/(commonjsGlobal || window || commonjsGlobal));
```

However, I didn't know if this was how it should be approached in the source file here: 
https://github.com/fluture-js/Fluture/blob/19febe13038ea5c9d6f2cc499d7b9052a334e611/src/internal/fn.js#L5

**Comment by wking-io** [comment]
I will be happy to make a PR myself to solve this issue just wanted to check in that it followed the protocol

**Comment by Avaq** [comment]
Oh good catch! That's specific to Node, how silly of me. Don't worry about a PR, I will fix it immediately.

**Comment by Avaq** [comment]
:point_up: There's the PR that should fix the issue.
