### ISSUE TITLE
Integration with Sanctuary does not work as stated in the docs

### ISSUE THREAD

**Issue by hbarcelos** [fluture-js/Fluture#211]
If I run this snippet:

```javascript
var {create, env} = require('sanctuary');
var {env: flutureEnv} = require('fluture-sanctuary-types');
var Future = require('fluture');

var S = create({checkTypes: true, env: env.concat(flutureEnv)});

S.I(Future.of(1));
```

I get:

```javascript
TypeError {
    message: `Invalid value␊
    ␊
    def :: String -> StrMap (Array TypeClass) -> NonEmpty (Array Type) -> Function -> Function␊
                                                                          ^^^^^^^^␊
                                                                             1␊
    ␊
    1)  undefined :: Undefined␊
    ␊
    The value at position 1 is not a member of ‘Function’.␊
    ␊
    See https://github.com/sanctuary-js/sanctuary-def/tree/v0.14.0#Function for information about the Function type.␊
    `,
  }
```

## Package versions

```
├── fluture@8.0.1
├── fluture-sanctuary-types@1.5.0
├── sanctuary@0.14.1
└── sanctuary-def@0.14.0
```

**Comment by Avaq** [comment]
Hello @hbarcelos,

Thank you for reporting this issue. Unfortunately I have not been able to reproduce it. If I run the exact same snippet using the same versions of these libraries, I get the expected result of `Future { _value: 1 }`.

I've tested by saving the snippet to a file `sanctuary-integration.js`, wrapping the last statement in `console.log` and running:

```sh
npm i sanctuary@latest fluture@latest fluture-sanctuary-types@latest
node sanctuary-integration.js
```

Some things I noticed which may provide clues:

* Your TypeError looks different from how it would look running it with Node. How are you running this code?
* The error message you see is thrown by `def`. Neither `fluture` nor `fluture-sanctuary-types` use this function, I believe. Are you using it somewhere?

**Comment by hbarcelos** [comment]
Hi @Avaq , thank's taking time to look into this.

You are right, I'm not using `node` to run it, this error actually appears only in a test suite running on `ava`.

A few things to consider here that might be related:

- I configured `ava` to transpile the source files on the fly using babel.
- The issue appears only if I use [`testdouble`](https://github.com/testdouble/testdouble.js) module stubbing function `td.replace` to replace **any** module.

This `td.replace` function monkey-patches the `require` native function from node.js, so this might cause some trouble.

I removed `fluture` integration and the issue is still there, so this must be related to `testdouble` or even `sanctuary`.

It's the first time I'm trying to use `fluture` and `sanctuary`, so I was feeling kind of lost. I'm sorry for not testing it thoroughly before creating the issue.

**Comment by davidchambers** [comment]
> It's the first time I'm trying to use `fluture` and `sanctuary`, so I was feeling kind of lost.

@hbarcelos, feel free to say hello and ask questions in the [Fluture][1] and [Sanctuary][2] rooms on Gitter. :)


[1]: https://gitter.im/fluture-js/Fluture
[2]: https://gitter.im/sanctuary-js/sanctuary

**Comment by hbarcelos** [comment]
Thank you @davidchambers. That'll be very helpful :smiley:
