### ISSUE TITLE
[feature] Add filterM to filter a list with a Future

### ISSUE THREAD

**Issue by nikogosovd** [fluture-js/Fluture#233]
Thank you for Fluture — excellent library!

What about a new feature — function `filterM`:
```
filterM :: Future m => (a -> m Bool) -> [a] -> m [a]
```
Its purpose is to filter a list with a function that returns a Future of boolean. Similar functionality is present in the [Bluebird promise](http://bluebirdjs.com/docs/api/promise.filter.html) library.

I see the following API:

```js
const predicateF = x => Future( (reject, resolve) => resolve(x === 1) );

Future.filterM(predicateF, [1,2,3,2,1]).fork(console.error, console.log);
//> [2,3,2]
```

**Comment by davidchambers** [comment]
That type signature isn't quite right, @nikogosovd. Is this what you have in mind?

```haskell
Future.filterM :: (a -> Future x Boolean) -> Array a -> Future x (Array a)
```

What would happen if the “predicate” rejects one or more of the array elements?

**Comment by nikogosovd** [comment]
@davidchambers I've used this type signature as a hint: http://hackage.haskell.org/package/base-4.10.1.0/docs/Control-Monad.html#v:filterM. What's wrong with the previously suggested signature? What are the key differences between the two?

The most obvious scenario in the case of at least one predicate rejection is to reject the entire computation. There are other scenarios which I found worse:

1.  Silently filter out values on which the predicate was rejected — semantics violations
2. Do not filter out such values — semantics violations
3. Replace such values with rejections — type signature violation

Any thoughts?

**Comment by davidchambers** [comment]
> What's wrong with the previously suggested signature?

```haskell
filterM :: Applicative m => (a -> m Bool) -> [a] -> m [a]
```

`Applicative m` is a type-class constraint. It states that `m` can be any type which satisfies the requirements of Applicative. `Future` is a type constructor, so cannot appear on the left of the `=>`.

**Comment by nikogosovd** [comment]
Got it, thank you.
If Future implements Fantasy Land `Monad` it also implements `Applicative`.

Do I understand correctly that the correct implementation of a `filterM` in the Fluture requires the Fantasy Land to have `filterM` in `Applicative`?

**Comment by Avaq** [comment]
I don't think `filterM` is for Fluture to implement (but I'm not sure yet, I'll have to think about it\*). It could be implemented by a library such as Ramda or Sanctuary. Sanctuary already has [`filter`](https://sanctuary.js.org/#filter) and [`filterM`](https://sanctuary.js.org/#filterM), but they are both different from what you need:

```hs
S.filter  :: (Applicative f, Foldable f, Monoid (f a)) => (a -> Boolean) -> f a -> f a
S.filterM :: (Alternative f, Monad f)                  => (a -> Boolean) -> f a -> f a
wanted    :: (Applicative f)                           => (a -> f Bool)  -> [a] -> f [a]
```

Perhaps @davidchambers is open to consider the `wanted` function as a candidate for Sanctuary Type Classes.

In the mean time, I guess you could use the less elegant solution:

```js
const predicateF = x => Future( (reject, resolve) => resolve(x === 1) )

const program = S.pipe([
  S.map(x => predicateF(x).map(ok => ok ? S.Right(x) : S.Left(x))),
  Future.parallel(42),
  S.rights
])

program([1,2,3,2,1])
```

----

\* If `wanted` would exist as implemented in Haskell, your code would still be somewhat verbose. This is why I'm considering adding `filter` to the library (similarly to how `parallel` is in the library even though we have `S.sequence`).

```js
const predicateF = x => Future( (reject, resolve) => resolve(x === 1) )

const program = S.pipe([
  S.wanted(S.compose(Future.Par, predicateF)),
  Future.seq
])

program([1,2,3,2,1])
```

**Comment by nikogosovd** [comment]
@Avaq Many thanks for your reply.

The first solution with `Future.parallel ` fits me well despite its verbosity.

I totally agree with you that both solutions are verbose. But the second one lacks explicit concurrency control. And it seems that `wanted` should implement Fantasy Land `Alternative` to be able to manage the concurrent application of `predicateF`.

I'm satisfied with the proposed solution, so if you are not going to implement `wanted` or haven't a more elegant solution, the issue can be closed.

**Comment by davidchambers** [comment]
> Perhaps @davidchambers is open to consider the `wanted` function as a candidate for Sanctuary Type Classes.

Feel free to open an issue for discussion. :)

**Comment by Avaq** [comment]
With the alternative solution being immediately accepted by the OP, and this issue gaining little further attention, I've decided to leave things as they are.
