### ISSUE TITLE
Dealing with Eithers

### ISSUE THREAD

**Issue by masaeedu** [fluture-js/Fluture#253]
There's been some questions in the Sanctuary chatroom recently about how to handle `Future e1 (Either e2 x)` values that arise where pure error handling functions interact with futures. The issue is that Fluture does two jobs; it contains a notion of asynchronicity as well as a notion of "either-ness". When you end up with an `Either` nested in a future you often want to "`join`" the two levels of `Either`-ness, which requires you to fold (using `S.either`) the `Either` into a future, or using `F.fold`, vice versa.

I think it would be good to have some advice in the docs on how to deal with this kind of situation. If needed, you might provide some conversion utilities. The approach I normally use (not sure how idiomatic), is:

```js
const eitherToFuture = S.either(F.reject)(F.of)

eitherToFuture(Right(42)) // :: Future a Number
eitherToFuture(Left("whoops")) // :: Future String b
```

Aside: I think it would be nice if there was a "non-error handling" Fluture on top of which consumers (including the Fluture library itself) can add any desired error handling strategy using monad transformers (you can recover `type Fluture e x` from `type NonErrorHandlingFluture x` as `type Fluture e x = EitherT e NonErrorHandlingFluture x`). After discussing this with @syaiful6 in the chatroom however, it seems this is not a universally popular idea, so take it with a pinch of salt.

**Comment by Avaq** [comment]
> The approach I normally use (not sure how idiomatic), is: [`S.either(F.reject)(F.of)`]

I use that approach too. I don't intend to make Sanctuary a dependency of Fluture, though. I would, however, like to put this stuff in a separate library, eg `sanctuary-with-fluture`. It could contain all the useful things like `eitherToFuture` and `maybeToFuture`, as well as all the Fluture functions typed with Sanctuary Def. I've been postponing this plan until after I modularise Fluture, though. It would be nice if `sanctuary-with-fluture` could build on top of a stripped-down version of Fluture to avoid double-currying, an unused fluent method API, that sort of stuff.

> I think it would be nice if there was a "non-error handling" Fluture

Fluture has always been "an alternative to Promises". It comes with Async, Either, and IO baked-in. It's meant to be used as a solution for the very common case (in Node) where you want the effect of Async, IO and Either all together (pretty much all i/o in Node is async and can fail).

I see the benefits of having separate access to these types. And once users of Fluture do too, I would expect them to switch to something like [`fp-ts`](https://github.com/gcanti/fp-ts). I would like for Fluture to remain an entry-level solution. A drop-in replacement to Promises that proves the benefits of *lazy* and *principled*. Knowing that the effect of Either will always be baked into Fluture, Fluture can also optimise around the idea of failure: there are several [mechanisms](https://github.com/fluture-js/Fluture/blob/9730064d78d61b29e36aa806ad7237261e836687/src/internal/interpreter.js#L73-L90) in place that "short circuit" your Future interpretations in the event of failure.

**Comment by Avaq** [comment]
> I would, however, like to put this stuff in a separate library

I've made note of these ambitions in the [Roadmap](https://github.com/fluture-js/Fluture/projects/3). For now I'll close this issue, as it is not immediately actionable.
