### ISSUE TITLE
d.ts problem at VS Code

### ISSUE THREAD

**Issue by trsdln** [fluture-js/Fluture#259]
Hey, 

Is it possible to fix this issue

https://github.com/Microsoft/vscode/issues/54165

**Comment by Avaq** [comment]
Ah. It may very well be in conflict with this line!

https://github.com/fluture-js/Fluture/blob/26be7e22cd02867cdfa1a764dfb1988db7d70efe/index.d.ts#L54

I was under the impression that types and values in TypeScript could have the same name, and TypeScript uses the appropriate meaning depending on the context it's used in. If that is not the case, the naming conflict can be easily resolved.

**Comment by Avaq** [comment]
> I was under the impression that types and values in TypeScript could have the same name

Of course it would be hard to disambiguate when the context could be either.

```ts
export interface Fluture { ... }
export interface Future<L, R> { ... }
export var Future: Fluture
export default Future // This is ambiguous.
```

**Comment by trsdln** [comment]
@Avaq 

Played around with it. Issue is gone after renaming exported variable to something else.

```
  const _Future: Fluture;
  export default _Future;
``

Looks like name conflict with `interface Future`

**Comment by trsdln** [comment]
Either exported variable should be renamed to something else or `interface Future<L, R> ` to `interface IFuture<L, R> `

**Comment by Avaq** [comment]
The exported variable matches the name of the actual export from the Fluture source, so it would have to be the interface to be renamed.

**Comment by mjbvz** [comment]
Yes looks like it changed recently. 7.1.2 has:

```ts
export const Future: Fluture
export default Fluture
```

**Comment by Avaq** [comment]
I believe renaming the interface will be a breaking change for some, in particular I have the `fp-ts` in mind:

https://github.com/gcanti/fp-ts-fluture/blob/96921017eb731b80ffc5a636eed7cb8498f5c4dc/src/Future.ts#L1-L15

I will include a fix in the next major release.
