### ISSUE TITLE
StackOverflow tag

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [fluture-js/Fluture#263]
Hello all, 

Following a previous discussion, I have added a tag for this project, called `fluture-js`. 

You may find it here:

https://stackoverflow.com/questions/tagged/fluture-js

I have also taken the liberty to add some tag information ( still under peer review ):

> What is Fluture-js ?
> From the official website:
> 
> Fluture offers a control structure similar to Promises, Tasks, Deferreds, and what-have-you. Let's call them Futures.
> 
> Much like Promises, Futures represent the value arising from the success or failure of an asynchronous operation (I/O). Though unlike Promises, Futures are lazy and adhere to the monadic interface.
> 
> Where can I get it?
> You may find more information about the project in it's official git repository:
> 
> https://github.com/fluture-js/Fluture

Please feel free to give me some feedback, suggestions and/or questions you may have.

If you are a StackOverflow fan, you may now watch the tag to be notified of any discussions that include it.

Feel free to let me know what you think, and share around ( on gitter and other channels ). 

-------

PS, if you have any corrections, now would be a good time.

**Comment by davidchambers** [comment]
Very nice, @Fl4m3Ph03n1x. Could the tag be named simply `fluture` rather than `fluture-js`?

**Comment by Fl4m3Ph03n1x** [comment]
Alright, I am following the standard proceadure for removal of small tags:

https://meta.stackoverflow.com/questions/363365/rename-a-tag-with-misspelled-name

So I have removed the new tag from all questions. Once I confirm that the tag was successfully deleted, I will create the new one called `fluture`.

I will keep this discussion updated in the meanwhile!

**Comment by Fl4m3Ph03n1x** [comment]
For additional info, this is what I plan to put on the tag information page:

**Usage guidance (excerpt)**
Fluture is a JavaScript library that  offers a control structure similar to Futures in other languages, but that are lazy, adhere to the monadic interface and are Fantasy Land compatible.

**Tag descriptions**
What is Fluture ?
-----

From the official website:

> Fluture offers a control structure similar to Promises, Tasks,
> Deferreds, and what-have-you. Let's call them Futures.
> 
> Much like Promises, Futures represent the value arising from the
> success or failure of an asynchronous operation (I/O). Though unlike
> Promises, Futures are lazy and adhere to the monadic interface.

Where can I get it?
-----

You may find more information about the project in it's official git repository:

https://github.com/fluture-js/Fluture

------

What do you guys think?

**Comment by Fl4m3Ph03n1x** [comment]
Done, I have created a new tag with all the suggestions !

https://stackoverflow.com/questions/tagged/fluture

You may now subscribe to `fluture`.
I know I will be watching questions pertaining to it, will you? :P

----

The description is still awaiting for a peer review, but you can already use the tag.
As usual, feel free to share and use !

PS: I will leave this discussion open until the peer review approves/rejects the tag description.

**Comment by Avaq** [comment]
Thank you @Fl4m3Ph03n1x. I have subscribed and enabled daily email notifications. That should be enough to make me aware of new Fluture questions.

**Comment by Fl4m3Ph03n1x** [comment]
@Avaq  Perhaps adding the badge on the README.md would be a good idea?

https://shields.io/

( Check for stackoverflow tag )

**Comment by Fl4m3Ph03n1x** [comment]
Tag documentation reviewed and approved!
It's official !

Should I make a PR to include the tag in the README.md ?

**Comment by Avaq** [comment]
> Should I make a PR to include the tag in the README.md ?

I'll do it as part of #264 :)

**Comment by Fl4m3Ph03n1x** [comment]
I will close this issue once your PR is accepted and published 😄
