### ISSUE TITLE
Fluture should have apRej

### ISSUE THREAD

**Issue by mfidemraizer** [fluture-js/Fluture#273]
Hi @Avaq!

I believe that `Future.apRej` would be a good addition, since we already have `Future.mapRej` and `Future.chainRej`.

**Comment by Avaq** [comment]
After some consideration, I think the use-case is too rare to justify inclusion of a new method. Generally, the failure branch has a simple value like an instance of `Error` or a string, and is not a common subject of transformation. Furthermore, there are three ways to "ap" with a failure branch: `failureFunction.ap(failureValue)`, `failureFunction.ap(successValue)`, and `successFunction.ap(failureValue)`. Each might have their occasional use-case, but I would not like including all of them.

With the inclusion of `pipe` to the library, however (#282), you will be able to fully utilise a custom written `apRej` suited to your own needs, eg:

```js
const apRej = mf => mx => mf.chainRej(f => mx.mapRej(x => f(x)));

Future.reject(21)
.mapRej(S.add)
.pipe(apRej(Future.reject(21)))
.done(console.error)
//! 42
```

Do you agree with my thinking, and shall we close this issue?

**Comment by mfidemraizer** [comment]
Yes, no problem. The `Future.pipe` thing is fine! Thank you
