### ISSUE TITLE
Cancel function not running in Future.parallel

### ISSUE THREAD

**Issue by jonwhelan** [fluture-js/Fluture#292]
When calling Future.parallel, the cancellation function is not called on futures in the array that are placed after an already rejected future:

```js
const makeFuture = (name) =>
	Future((rej, res) => {
		setTimeout(() => res(name), 100);
		return () => {
			console.log(`cancelling ${name}`);
		}
	});

Future.parallel(Infinity, [
	makeFuture('A'),
	Future.reject(new Error),
	makeFuture('B')
]).fork(console.error, console.log);
```

```
Expected:
  'cancelling A'
  'cancelling B'

Actual:
  'cancelling A'
```

**Comment by Avaq** [comment]
Hi @jonwhelan,

Thank you for taking the trouble to file a report. This is expected behaviour, however.

`Future.reject` creates a Future which *immediately* rejects the very tick it is forked in. This means that as `Future.parallel` is forking the Futures one by one, the moment it encounters your rejected Future is knows that it can stop. In other words, the third Future never even ran - it doesn't need to be cancelled.

Try and see what happens if you use `Future.rejectAfter(1, new error)` instead. :)

**Comment by Avaq** [comment]
You can also see this nicely if you would add a log line when the Future starts executing:

```diff
 const makeFuture = (name) =>
   Future((rej, res) => {
+    console.log(`running ${name}`)
     setTimeout(() => res(name), 100);
     return () => {
       console.log(`cancelling ${name}`);
     }
   });
```

**Comment by jonwhelan** [comment]
Thanks for getting back quickly with an explanation! I played around with it some more after submitting the issue to come up with a more accurate example of my setup. Just posting this for sake of discussion should anyone run across this.

```js
const chainedFuture = Future((rej, res) => {
		setTimeout(() => res('test'), 100);
		return () => {
			console.log(`cancelling 1`);
		};
	}).chain((val) =>
		Future((rej, res) => {
			return () => {
				// This doesn't get called
				console.log(`cancelling 2`);
			};
		})
	);

Future.parallel(Infinity, [
	chainedFuture,
	Future.rejectAfter(1, new Error()),
]).fork(console.error, console.log);
```

In this one, the `chainedFuture` is before the rejected future in the array so the "issue" doesn't necessarily depend on the order of the futures in the array. What made this behavior unexpected for me was that I thought `chainedFuture` would be handled as one "whole" future and thus both would run and be cancelled, but it makes sense that only the first future runs and is then cancelled before the second future is able to be forked.
