### ISSUE TITLE
Rename fold to coalesce

### ISSUE THREAD

**Issue by Avaq** [fluture-js/Fluture#324]
See https://github.com/folktale/data.task/issues/41#issuecomment-339595974 (via #173). In a nutshell, what most functional programmers think `fold` means is not quite the same as what `fold` in Fluture *does*.

Fluture cannot implement "real `fold`", because there's no way in plain JavaScript to force the thread to block until a callback is called.

I've browsed through some aliases, etymology, and related words to `fold`, and believe a good replacement candidate could be `collate` (open to suggestions!): Essentially what the function does is to unify the two different types on both branches into one type on one branch.

**Comment by Avaq** [comment]
I don't think collate is a good name.

**Comment by Avaq** [comment]
Crocks calls it `coalesce`, which is also how it, in a sense, is called in Postgres. I think that might be a good option.

**Comment by fakenickels** [comment]
Coalesce looks like a good name!

>Fluture cannot implement "real fold"
what do you mean by real fold?

**Comment by Avaq** [comment]
> Coalesce looks like a good name!

I'm warming up to it. :)

> what do you mean by real fold?

Typically, `fold` unwraps the value, but a Future can't be unwrapped without a continuation, so `Future.fold` returns the value in a Future.

```hs
Typical.fold :: (a -> c) -> (b -> c) -> Typical a b ->          c
Future.fold  :: (a -> c) -> (b -> c) -> Future  a b -> Future d c
```

**Comment by fakenickels** [comment]
aah now I got it! thanks for the clarification
