### ISSUE TITLE
Improve the promise function

### ISSUE THREAD

**Issue by Avaq** [fluture-js/Fluture#331]
The current function signature is not true to reality:

```hs
promise :: Future a b -> Promise b a
```

The rejection branch of a Promise is not considered "typed" in the same way that `catch (e)` statements are untyped. Anything can be thrown. The `Promise b a` in the signature there is made up. Typically Promises are considered unary types. Practically users have come to expect the rejection branch to contain an instance of `Error`, similarly to `catch (e)`.

To uphold this signature, however, Fluture is forced to `throw` its exception whenever `promise` was called on a crashed Future. A better flow would be to pass the exception into the Promise' rejection branch, in the spirit of Promises.

To accommodate for this change, I propose changing the signature of `promise`:

```hs
promise :: Future Error a -> Promise a
```

We can see what's happening here:

1. We're forcing users to call `Promise` on Futures that have *Error* in their rejection branch *only*.
2. Now both the exception branch *and* the rejection branch can be merged into the rejection branch of the Promise, in the spirit of Promises.
3. Our Promise type is no longer made up.

---

Since merging user-land errors with runtime exceptions is generally a bad idea, I will urge users to use `fold` before `promise` to keep rejections separate from crashes. If users have a non-`Error` type in their rejection branch, they will be forced to do this anyway.

---

I think this change caters to two audiences at the same time:

1. Those who were already using the rejection branch for Error instances and don't mind merging them with runtime exceptions when casting to a Promise.
2. Those who keep their rejections separate from their crashes, but were not able to use `promise` because their crashes would've been thrown.

**Comment by edgarjrg** [comment]
In `fluture@12.0.0-beta.3` the type of `promise` is 
```ts
export function promise<R>(source: FutureInstance<Error, R>): Promise<R>
```

That makes very cumbersome the transformation from Fluture to Promise, I get the reasoning, but many libraries/users do not put an `Error` in `Promise` rejection branch, and typescript lib.es5 types `catch` as 

```ts
catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): Promise<T | TResult>;
```

So the reason is `any` in either way.

Maybe we should be more flexible and type it 

```ts
  export function promise<R>(source: FutureInstance<any, R>): Promise<R>
```

**Comment by Avaq** [comment]
I understand where you're coming from. If all Fluture would do is move the rejection branch from a Future into the Promise rejection branch, then I think it's a good suggestion.

However, besides putting the rejection reason, Fluture also puts runtime exceptions into the rejection branch. For example:

```js
promise (Future (() => {
  throw new Error ('I like to break things!')
}))
```

This would result in a rejected Promise with the Error in the rejection branch. That's because Fluture caught the error and assumed a "crashed" state. One can only recover from this state by consuming the Future. When the Future is consumed by the `promise` function, the Error is moved into the Promise rejection branch.

The reason Fluture wants your rejection branch to have type Error before calling `promise` is so that you don't force Fluture to mix types. Fluture is built with the philosophy that mixing types is bad, and so to have a function that goes against its own philosophy might go against user expectations.

The ideal situation would be if a users could simply do this:

```js
reject (42) |>
fold (Left) (Right) |>
promise
```

And then TypeScript infers that after `fold`, the type of the rejection branch ([`unknown`?](https://github.com/fluture-js/Fluture/issues/370#issuecomment-533226653)) is assignable to Error, and you as a user get all your values neatly separated. The promise rejects on crash, and resolved with `Either Number a`, where `Number` is the rejection reason, and `a` the unknown resolution value.
