### ISSUE TITLE
Flip Future.and

### ISSUE THREAD

**Issue by codingedgar** [fluture-js/Fluture#365]
Hi ! Such a great library, thank you ! 🙏 

I'm seeing this behavior 

```ts
test(
    'resolve(x).and(resolve(y)) === resolve(x).pipe(and(resolve(y)))',
    (done) => {
      resolve('R')
        .and(resolve('L'))
        .fork(
          fail,
          x => {
            expect(x).toBe('L')

            resolve('R')
              .pipe(and(resolve('L')))
              .pipe(fork(
                fail,
                y => {

                  expect(y).toBe('L') // failed: received R

                  expect(x).toBe(y) // failed
                  done()
                }
              ))

          },
        )
    })
```
i tried all the combinations for `FlutureR.and(FlutureL) === FlutureR.pipe(and(FlutureL) `.

```
✕ resolve(x).and(resolve(y)) === resolve(x).pipe(and(resolve(y))) (2ms)
✓ resolve(x).and(reject(y)) === resolve(x).pipe(and(reject(y))) (1ms)
✕ reject(x).and(reject(y)) === reject(x).pipe(and(reject(y))) (1ms)
✓ reject(x).and(resolve(y)) === reject(x).pipe(and(resolve(y)))
```

`FlutureA.and(FlutureB)` seems to work like documented, here `and` is expecting a Left, but with `pipe`, `and` expects the right Fluture which seems odd for currying.

Why is different `Fluture.and` from `and`?, if i use pipe, i still would expect FlutureR to resolve first than FlutureL, i made a workaround by using `FlutureR.pipe(flip(and)(FlutureL))`.

Sorry for my lack of understanding 🙏 

Thanks in advance.

**Comment by Avaq** [comment]
> Such a great library, thank you ! :pray:

Thank you! :D

> Why is different `Fluture.and` from `and`?

For legacy reasons. This problem has been corrected in the latest beta version of Fluture (`npm i fluture@beta`) and will be included as part of version 12, alongside many other breaking changes. You can [see the migration guide here](https://gist.github.com/Avaq/ee2c6c819db4c37258e9a226e6380a38).

> i made a workaround by using `FlutureR.pipe(flip(and)(FlutureL))`

That is the right approach for now, in case you want to stay on stable.
