### ISSUE TITLE
Typescript errors for go blocks

### ISSUE THREAD

**Issue by tschmidt64-SC** [fluture-js/Fluture#366]
I am running a minimal typescript setup using npm. I cannot get the types for go blocks to work. Here is the simple code that I'm running and the compile error it generates:

```typescript
import { resolve, go } from 'fluture'

const func = () => go (function* () {
    return yield resolve (1)
})
```

Error:
```
[eval].ts:2:24 - error TS2345: Argument of type '() => Generator<FutureInstance<unknown, number>, number, FutureInstance<L, any>>' is not assignable to parameter of type 'Generator<FutureInstance<unknown, any>, FutureInstance<unknown, number>>'.
  Type 'Generator<FutureInstance<unknown, number>, number, FutureInstance<L, any>>' is not assignable to type 'Iterator<FutureInstance<unknown, any>, FutureInstance<unknown, number>>'.
    Types of property 'next' are incompatible.
      Type '(...args: [] | [FutureInstance<L, any>]) => IteratorResult<FutureInstance<unknown, number>, number>' is not assignable to type '(value?: FutureInstance<unknown, any>) => Next<FutureInstance<unknown, any>> | Done<FutureInstance<unknown, number>>'.
        Type 'IteratorResult<FutureInstance<unknown, number>, number>' is not assignable to type 'Next<FutureInstance<unknown, any>> | Done<FutureInstance<unknown, number>>'.
          Type 'IteratorYieldResult<FutureInstance<unknown, number>>' is not assignable to type 'Next<FutureInstance<unknown, any>> | Done<FutureInstance<unknown, number>>'.
            Type 'IteratorYieldResult<FutureInstance<unknown, number>>' is not assignable to type 'Done<FutureInstance<unknown, number>>'.
              Property 'done' is optional in type 'IteratorYieldResult<FutureInstance<unknown, number>>' but required in type 'Done<FutureInstance<unknown, number>>'.
```

package.json:
```javascript
{
  "name": "ipfs-playground",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "npm run build && node dist/app.js",
    "debug": "npm run build && node --nolazy --inspect-brk=0.0.0.0:9229  dist/app.js",
    "build": "tsc"
  },
  "dependencies": {
    "@types/node": "^12.7.3",
    "fluture": "^12.0.0-beta.3",
    "ts-node": "^8.3.0",
    "typescript": "^3.6.2"
  }
}
```
tsconfig.json:
```javascript
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES2015",
        "declaration": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "outDir": "dist",
        "strict": true,
        "baseUrl": "."
    }
}
```

**Comment by Avaq** [comment]
Thank you for reporting this issue. I don't have the time to look into it right now, but I'll let you know when I do. I would welcome a PR that solves it, of course! ;)

**Comment by Avaq** [comment]
@tschmidt64-SC Looking at the TypeScript error message, it seems to be complaining about the way `func` is being used. The `func` function is not being used in your snippet though. Is the code you shared the whole thing? If not, could you share the context you extracted it from?

**Comment by Avaq** [comment]
Further analysis suggests that TypeScript is trying to use two different, incompatible, definitions of the `Generator` type to check this code. The incompatibility seems to hinge on the `done` property of the `IteratorResult`, which in Fluture is considered mandatory, and perhaps in TypeScript's own definition of a generator is not.

**Comment by Avaq** [comment]
It would probably be better for Fluture to use TypeScript's built-in `Generator` type. Currently it's rolling its own definition:

https://github.com/fluture-js/Fluture/blob/88f9a9f26d846f02bd539b39ef809dbbc2704cfd/index.d.ts#L23-L39

I don't know how to import and use TypeScript's built-ins, though. I can't actually figure out where these incompatible type definitions are coming from. These docs don't tell me much: https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html

Maybe you can help me with this, @tschmidt64-SC.

**Comment by tschmidt64-SC** [comment]
I’m out of town on holiday right now but I’ll look into it this Thursday when I get back :)

**Comment by OliverJAsh** [comment]
> I can't actually figure out where these incompatible type definitions are coming from.

They are global so you don't need to import them. They live in `node_modules/typescript/lib/lib.es2015.iterable.d.ts`, which is included in the TS project if you specify `lib: ['es2015']` as a compiler option.
