### ISSUE TITLE
Can't run examples for `ap`

### ISSUE THREAD

**Issue by anatoliyarkhipov** [fluture-js/Fluture#387]
Hey! I'm trying to figure out how `ap` works but had no luck trying to run examples from the readme. For example, that one, looking like the simplest one:
```js
fork (log ('rejection'))
     (log ('resolution'))
     (ap (resolve (7)) (ap (resolve (49)) (resolve (x => y => x - y))))
```

When I try to run it, I get an error:
```
Error: Future#ap() expects its first argument to be a Future of a Function
  Actual: Future.of(7)
```

Here is an interactive example: https://runkit.com/aarkhipov/5db0b41997ed0d001b5195ec

The only workable version I managed to figure out is with a single future, which I believe is not the point of `ap`, since it's supposed to "combine the success values of multiple Futures using a function". 
```js
fork (log ('rejection'))
     (log ('resolution'))
     (ap (resolve (y => y - 7), resolve (49)))
```

This example doesn't throw and logs to the console:
```
"resolution:42"
```

I also found issues #24 and #87 that seem related, but I'm new to that stuff and still incapable to figure that out on my own.

**Comment by dicearr** [comment]
Which version of Fluture are you using?

In the beta version `12.0.0`, which you can install with `npm install fluture@beta`, issue #24 has been solved and `ap` signature looks like this: `ap :: Apply m => m a -> m (a -> b) -> m b`. That means, function last.

```js
const {resolve, ap, fork} = require ('fluture')
const pkg = require ('./node_modules/fluture/package.json')

console.log (pkg.version)
// 12.0.0-beta.4

fork (x => console.log ('Rejection', x)) 
     (x => console.log ('Resolution', x)) 
     (ap (resolve (1)) (resolve (x => x + 1)))
// Resolution 2
```

If you have ran `npm install fluture` then you're using version `11.x`. Checking the documentation the signature of `ap` is `ap :: Apply m => m (a -> b) -> m a -> m b` and that means function first.

```js
const {resolve, ap, fork} = require ('fluture')
const pkg = require ('./node_modules/fluture/package.json')

console.log (pkg.version)
// 11.0.3

fork (x => console.log ('Rejection', x))
     (x => console.log ('Resolution', x))
     (ap (resolve (x => x + 1)) (resolve (1)))
// Resolution 2
```

About "combine the success values of multiple Futures using a function" you need to use `ap` twice. Assuming that you're using version `11.x` the code would look like this:

```js
const {resolve, ap, fork} = require ('fluture')
const pkg = require ('./node_modules/fluture/package.json')

console.log (pkg.version)
// 11.0.3

fork (x => console.log ('Rejection', x))
     (x => console.log ('Resolution', x))
     (ap (ap (resolve (x => y => x + y)) (resolve (1))) (resolve (2)))
// Resolution 3
```

The idea is that with the inner `ap` the function gets partially applied with `1` and the result is a future containing a unary function. Then you can use `ap` again to apply this function with the next argument.

**Comment by anatoliyarkhipov** [comment]
Yeah, you're right, I'm using 11.x and the funny thing is that it seems I had read the whole README _except_ the very first paragraph, going immediately after the BETA warning:
> You're looking at the beta version of the Fluture documentation. For the stable version, please consult the 11.x branch. If you're interested in upgrading to the new version, check out the upgrade guide!

So, to sum up, my problem was that I tried examples for other version.
