### ISSUE TITLE
Unexpected TypeScript type error when using `value` due to `this`

### ISSUE THREAD

**Issue by OliverJAsh** [fluture-js/Fluture#389]
```ts
import Future, * as fluture from 'fluture';
/*
The 'this' context of type 'FutureInstance<unknown, number>' is not assignable to method's 'this' of type 'FutureInstance<never, number>'.
  Type 'unknown' is not assignable to type 'never'.
*/
fluture.of(1).value(n => { console.log(n) });
```

I think `this` inside of `value`  should be typed to typed to use `unknown` for errors instead of `never`?

```diff
-    value(this: FutureInstance<never, R>, resolve: ResolveFunction<R>): Cancel
+    value(this: FutureInstance<unknown, R>, resolve: ResolveFunction<R>): Cancel
```

**Comment by Avaq** [comment]
This issue, and related issues, have been fixed in the latest beta version of Fluture. They cannot be merged into stable though, because they are breaking changes.

The work-around for stable is to manually set the type when calling `fluture.of`:

```ts
fluture.of<never, number>(1).value(n => { console.log(n) });
```

**Comment by Avaq** [comment]
Version 12 has been released out of beta. The following code works without TypeScript errors:

```ts
import * as fl from 'fluture'

fl.value (console.log) (fl.resolve (1))
```

I'm closing this issue. Feel free to comment if you find anything else.
