### ISSUE TITLE
TypeScript error when chaining with an encased function

### ISSUE THREAD

**Issue by protoEvangelion** [fluture-js/Fluture#392]
TypeScript is throwing this error when encasing node's `readdir` function with `encaseN` and giving it the Left path type of `NodeJS.ErrnoException`: 

```
Type 'FutureInstance<string, string>' is not assignable to type 'FutureInstance<ErrnoException, string>'
```

```javascript
const safeReaddir = Future.encaseN<NodeJS.ErrnoException, string[], string>(fs.readdir)

safeReaddir(cmdDir).chain(filterFiles)

function filterFiles(files: string[]): Future.FutureInstance<string, string> {}
```

Adding `any` to the type def in encaseN fixes the error:

```javascript
const safeReaddir = Future.encaseN<any, string[], string>(fs.readdir)

```

_Is this the right approach or is this an issue_?

**Comment by Avaq** [comment]
This issue has come up many times. It has little to do with `encase`, and everything to do with `chain`. Strictly speaking, using `chain` n Futures with two different rejection types is like using `chain` on two different Monads altogether.

However, it will change for practical reasons with Fluture version 12 (which is already released in beta). Have a look at the links in this comment: https://github.com/fluture-js/Fluture/pull/374#issuecomment-535080608 for more information.

**Comment by protoEvangelion** [comment]
Thanks for the thorough answer! I'll let you know if I run into any other problems with it 👍
