### ISSUE TITLE
Is it okey to use fluture for not async tasks?

### ISSUE THREAD

**Issue by mohsensaremi** [fluture-js/Fluture#396]
I am using `fluture` for my async tasks.
The question is Can I use `fluture` for all of my task? async and sync?
Is this cause some performance issue or something like that? 
Should I use `sanctuary` for not async task or do all of them with `fluture`?

**Comment by Avaq** [comment]
Yes. You can. The only drawback is that the Fluture type provides no way to synchronously get at your value. So even if a Future is completely synchronous:

```js
const completelySynchronousFuture = resolve (42)
```

Then still you need a continuation (a callback) to access that value:

```js
fork (console.error)
     (value => /* I need this callback to access value */)
     (completelySynchronousFuture)
```

----

When you're using `Either` (from Sanctuary for example), then you can extract the value from the structure directly:

```js
const completelySynchronousEither = Right (42)

// No callback needed:
const value = fromEither (0) (completelySynchronousEither)
```

**Comment by Avaq** [comment]
I'm closing this issue as it is not currently actionable.
