### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by Ne4to777** [fluture-js/Fluture#405]
```js
const m = resolve (1)

> for (const i = 0; i < 100000; i++) {
.   m = map (add1) (m)
. }
```

Assignment to constant (m, i)

**Comment by Avaq** [comment]
Oh, indeed! Thank you. This was probably introduced with the conversion from ES5 to ES6. Will you open a PR, or should I?

**Comment by Ne4to777** [comment]
I don`t understand what you mean.

Another misunderstanding in the absence of function 'log'. It is understood that it is imported from 'fluture', but in fact it needs to be implemented independently.

**Comment by Avaq** [comment]
The log function will eventually come from Doctest. See https://github.com/davidchambers/doctest/pull/118. You can just think of it as any log function. It doesn't matter.

**Comment by Ne4to777** [comment]
> You can just think of it as any log function

Yes, I understand, but I just want to copy and paste example code and do it work.
