### ISSUE TITLE
Can`t realize ap composition

### ISSUE THREAD

**Issue by Ne4to777** [fluture-js/Fluture#406]
Fantasy Land spec:
`v.ap(u.ap(a.map(f => g => x => f(g(x)))))` is equivalent to `v.ap(u).ap(a)` (composition)

Implementation:

`const v = resolve(1)`
`const u = resolve(x => x + 3)`
`const a = resolve(x => x * 3)`

`fork(log('rejection'))(log('resolution'))(`
`	ap(v)(ap(u)(map(f => g => x => f(g(x)))(a)))`
`) // OK`

`fork(log('rejection'))(log('resolution'))(`
`	v`
`		.pipe(ap(u))`
`		.pipe(ap(a))`
`) // TypeError: ap expects the second Future to resolve to a Function`

**Comment by Avaq** [comment]
I think you might be reading an outdated version of the Fantasy Land spec. Since version 1.0, Fantasy Land has required compliant methods to be prefixed:

> `v['fantasy-land/ap'](u['fantasy-land/ap'](a['fantasy-land/map'](f => g => x => f(g(x)))))` is equivalent to `v['fantasy-land/ap'](u)['fantasy-land/ap'](a)`
> -- https://github.com/fantasyland/fantasy-land#apply

You'll find that `v['fantasy-land/ap']` will behave as expected.

**Comment by Ne4to777** [comment]
Does the ap method not meet the requirements of fantasy-land? If so what specification is it using?

**Comment by Avaq** [comment]
The `fantasy-land/ap` method follows the specification. The `ap` function is a polymorphic dispatcher which dispatches to `fantasy-land/ap`. There is no specification for dispatchers. Library authors are free to implement them as they see fit.

**Comment by Ne4to777** [comment]
As I understand ap fallbacks to fantasy-land/ap only if context is not Future, right?

**Comment by Avaq** [comment]
That's an optimization for performance and begging reasons made within the Fluture code. It does not alter the behaviour of `ap` compared to what it would be as a plain dispatcher to `m['fantasy-land/ap']`.

**Comment by Avaq** [comment]
In other words, the following code can be removed:

https://github.com/fluture-js/Fluture/blob/9e8084eefb08c72d0f65352445a80a4791e60983/src/ap.js#L9-L15

...And all unit tests except the ones related to error messages and debugging will still pass.
