### ISSUE TITLE
Is it proven that Fluture Future is lawful?

### ISSUE THREAD

**Issue by kindaro** [fluture-js/Fluture#408]
I am sorry if it is written on the box, but I am not seeing. The readme is lengthy, but it discusses usage, and I could not find anything about laws or proofs thereof.

I do not ask for iron cast proofs, but maybe some outline.

**Comment by Avaq** [comment]
The README [points to](https://github.com/fluture-js/Fluture#interoperability) the [Fantasy Land specification](https://github.com/fantasyland/fantasy-land), where the laws are recorded.

Fantasy Land provides a set of property tests named [Fantasy Laws](https://github.com/fantasyland/fantasy-land), allowing authors to include these in their test suits. The best place to look for proof is probably [Fluture's property tests](https://github.com/fluture-js/Fluture/tree/master/test/prop), where Fantasy Laws is included.

**Comment by kindaro** [comment]
@Avaq Thank you. Would it be correct to say that, while extensive checking of laws is performed, no attempt is made to provide written proof, say via equational reasoning?

**Comment by Avaq** [comment]
I'm not sure exactly what you're looking for when you say "written proof", so probably you're right in your assumption. What exactly would you like to see proven?

**Comment by Avaq** [comment]
I'm closing this issue, as I don't see how I can act on it further. Feel free to reopen it if you have other questions.
