### ISSUE TITLE
Event Streams handling

### ISSUE THREAD

**Issue by krzysztofpniak** [fluture-js/Fluture#421]
I know there are libraries like @most/core, but is seems they don't implement fantasy-land.
I'm wondering if it is possible to handle streams with fluture. Is there any pattern I can use?

**Comment by Avaq** [comment]
You can use a lazy sequence of Futures to approximate a Stream.

You could use, for example, something like https://github.com/francisrstokes/Lazy-Infinite-List, and have a producer that emits Futures, process the stream by mapping, and consuming with [`go`](https://github.com/fluture-js/Fluture#go). Like so:

```js
const Infinite = require ('lazy-infinite')
const fl = require ('fluture')

const stream = Infinite.of (function*() {
  let x = 0
  while (true) yield Future.after (300) (x++)
})

// to process items in the stream, we can just mapmap:
const processedStream = fl.map (fl.map (x => `This is number ${x}`)) (stream)

// and then to consume, we can use go
fl.promise (fl.go (processedStream.gen))
```

----

In theory you should also be able to get Stream behaviour by using a List Monad Transformer:

```js
const Stream = List.Transformer (Future)
```

But I don't know of any packages that implement the list transformer. :man_shrugging:

**Comment by krzysztofpniak** [comment]
@Avaq Thanks for the quick response. Your advice looks very interesting. I'm not closing the issue for now because it is very fresh. Let's see if there are any other approaches.

**Comment by krzysztofpniak** [comment]
@Avaq I realized that your solution produces a constant stream of data. Could you guide me how to implement a source of real events like button clicks?

**Comment by krzysztofpniak** [comment]
Anyways I found a solution.
```js
const fromEvent = subscribe =>
  Future((reject, resolve) => {
    return subscribe(resolve);
  });

const eventStream = subscribe =>
  Infinite.of(function*() {
    let currentEmitter = () => {};
    subscribe(x => currentEmitter(x));
    const localSubscribe = emitter => {
      currentEmitter = emitter;
      return () => {};
    };
    while (true) {
      yield fromEvent(localSubscribe);
    }
  });

const stream = eventStream(emitter => {
  document.addEventListener("keyup", e => emitter(e));
  return document.removeEventListener("keyup", emitter);
});

// to process items in the stream, we can just map-map:
const processedStream = map(map(x => `Key Code = ${x.keyCode}`))(stream);

// we can also map-chain to process with a side effect or async thing:
const effectStream = map(
  chain(
    encase(x => {
      console.log(x);
    })
  )
)(processedStream);

// and then to consume, we can use go
promise(go(effectStream.gen));
```
Maybe it will help someone. **Please note that unsubscribe is not fully implemented.**

**Comment by Avaq** [comment]
I'm closing this issue as there are no further actions to take. Feel free to reopen it if your question has not been sufficiently answered.
