### ISSUE TITLE
Any future for Fluture on React Native?

### ISSUE THREAD

**Issue by mnhthng-thms** [fluture-js/Fluture#437]
Do you have any interest in introducing a Fluture package for React Native?

**Comment by Avaq** [comment]
Hi @mnhthng-thms! I have little experience with React Native. Is there any reason Fluture doesn't *already* run in a React Native environment?

**Comment by mnhthng-thms** [comment]
When I tried to import Fluture into Expo's managed-flow React Native project, I got a error message that the package lacks native modules for Android & iOS. 

I've done some experiments with Fluture on vanilla JS project for web development and I really really love it. Considering React Native, I've been learning it for 5 weeks and the only occasions I felt like needing Fluture are when I worked with Axios and Fetch API. Tbh, I'm not experienced and imaginative enough to see when Fluture is an essential for React Native project.

**Comment by dicearr** [comment]
I cannot reproduce the issue. I have used Expo's playground snack.expo.io to add Future and it seems to work perfectly. Have I misunderstood something?

You can download the source code and try locally with the commented out code. https://snack.expo.io/BHZTGSuzeq

**Comment by Avaq** [comment]
Closing this after a month of inactivity. Feel free to reopen it if anything new comes up, @mnhthng-thms.
