### ISSUE TITLE
Expose non monadic version of Future

### ISSUE THREAD

**Issue by safareli** [fluture-js/Fluture#44]
It will be nice to expose non monadic version of Future for which `ap` would be parallel.
This version could also implement [Alternative](https://github.com/fantasyland/fantasy-land/pull/197) where `alt` would be `race`

**Comment by Avaq** [comment]
:information_source: I'm working on this.

**Comment by Avaq** [comment]
I'm looking into developing this as its own package, extending Fluture with an optional Parallel structure. Some of Flutures core functionality will also be separated out to serve as a base for both packages.

**Comment by safareli** [comment]
@Avaq why?

So you are planning to have 3 repos like this?:
- Avaq/Fluture-core
- Avaq/Fluture
- Avaq/FluturePar

**Comment by Avaq** [comment]
> why?

In writing a detailed response about my reasons, I realized there may be some issues with this approach (circular dependencies, shared code). I'm going to drop the idea, and keep it in the same package.

**Comment by safareli** [comment]
After discussing this offline, here is what we came to:

As there is [Concurrently](https://hackage.haskell.org/package/async-2.1.1/docs/Control-Concurrent-Async.html) in haskell:
```hs
newtype Concurrently a = Concurrently { runConcurrently :: IO a }

instance Functor Concurrently where
  fmap f (Concurrently a) = Concurrently $ f <$> a

instance Applicative Concurrently where
  pure = Concurrently . return
  Concurrently fs <*> Concurrently as =
    Concurrently $ (\(f, a) -> f a) <$> concurrently fs as

instance Alternative Concurrently where
  empty = Concurrently $ forever (threadDelay maxBound)
  Concurrently as <|> Concurrently bs =
    Concurrently $ either id id <$> race as bs
```

We could have something like this:
```js
const mkConcurrently = (TaskRep, concurrently, race, zero) => {
  const Concurrently = daggy.tagged('run')
  Concurrently[fl.zero] = zero
  Concurrently[fl.of] = (a) => Concurrently(TaskRep[fl.of](a))
  Object.assign(Concurrently.prototype, {
    [fl.map](f) {
      return Concurrently(this.run[fl.map](f))
    },
    [fl.ap](a) {
      return Concurrently(concurrently(this.run,a))
    },
    [fl.alt](a) {
      return Concurrently(race(this.run, a))
    },
  })
  return Concurrently
}
```

which could be used with any Task/Future/whatever.

example with Fluture:
```js
const Par  =  mkConcurrently(
  Fluture, 
  (a,b)  => a.par(b),
  (a,b)  => a.race(b),
  Fluture.never
)

Par(Fluture.after(300, 1))[fl.alt](Par(Future.of(2)))
  .run.fork(log, log)
```

**Comment by safareli** [comment]
I think using names in spirit of [purescript-parallel](https://github.com/purescript/purescript-parallel/blob/master/src/Control/Parallel/Class.purs) would be better:
```diff
-const Concurrently = daggy.tagged('run')
+const Parallel = daggy.tagged('sequential')
```

```diff
Par(Fluture.after(300, 1))[fl.alt](Par(Future.of(2)))
-  .run.fork(log, log)
+  .sequential.fork(log, log)
```

**Comment by Avaq** [comment]
I created https://github.com/fluture-js/concurrify for this purpose. I'm working on the implementation now. Your thoughts?

**Comment by safareli** [comment]
That's nice! 

what you think if we move that to FantasyLand, as fantasy-concurrify for example?

**Comment by Avaq** [comment]
I'm creating it with the design decisions made for Fluture in mind. I'm not sure if it's too opinionated to host under FantasyLand (eg; the inclusion of `@@type`). Let's discuss it there: https://github.com/fluture-js/concurrify/pull/1

**Comment by Avaq** [comment]
The next step, I think, would be to depend on [concurrify](https://github.com/fluture-js/concurrify) and expose `Future.Par :: Future a b -> ParallelFuture a b` and `Future.seq :: ParallelFuture a b -> Future a b`.
