### ISSUE TITLE
Consider preserving the specific Error sub-type when converting to Promise

### ISSUE THREAD

**Issue by iliocatallo** [fluture-js/Fluture#446]
Hi,

Given some custom error:

```javascript
class CustomError extends Error {}
```

I realized that obtaining a `Promise` from a rejected `Future` preserves custom error types:

```javascript
Future.promise(Future.reject(new CustomError())); // => Promise {  <rejected> CustomError ... 
```

Whereas `throw`ing does not:

```javascript
Future.promise(new Future(() => { throw new CustomError(); })); // => Promise {  <rejected> Error ...
```

I was wondering if there's a rationale for this.  I get from #331 that the left-hand side of the resulting promise is constrained to be an `Error`. Nevertheless, it would be useful to preserve specialization – so as to, e.g., dispatch on the type of the error in the outer layers of the application.  

Thank you!

**Comment by Avaq** [comment]
I recommend using `Future.coalesce` before you run `Future.promise`. See also the [v12 upgrade guide](https://gist.github.com/Avaq/ee2c6c819db4c37258e9a226e6380a38#promise-function-reworked):

```js
// You probably have a library with this:
const compose = f => g => x => f (g (x))

// And likely also these:
const Left = x => ({success: false, value: x})
const Right = x => ({success: true, value: x})

// So you define your own promise function which coalesce's your branches first:
const attempt = Future.coalesce (Left) (Right)
const promise = compose (Future.promise) (attempt)

// And use it like this:
promise (Future.resolve (42)) // => Promise { <resolved> { success: true, value: 42 } }
promise (Future.reject (new CustomError ())) // => Promise { <resolved> { success: false, value: CustomError } }
promise (new Future(() => { throw new Error (); })) // => Promise { <rejected> Error }
```

**Comment by Avaq** [comment]
> I was wondering if there's a rationale for this.

When you throw something in the context of a Future, it is considered to be a bug in your program. In previous versions of Fluture, the exception was not caught, and would typically crash the program, or be caught by a global exception handler. Fluture didn't do anything to accommodate this: throwing an exception in an async program usually leads to this behaviour by default.

At some point, Fluture was updated to catch these exceptions for the purposes of debugging. They are still considered indications of bugs, but you have access to them now so you can investigate your bug more easily. The "crash" branch is exposed to the Promise rejection branch because that's how promises are modelled: bugs are supposed to go into the Promise rejection branch.

Since these exceptions are used for debugging only, and not to be used for program control flow, Fluture normalizes them into a single type.

**Comment by iliocatallo** [comment]
Hi Aldwin,

Thank you for the pointer and the explanation. Regarding your last point:

> Since these exceptions are used for debugging only, and not to be used for program control flow, Fluture normalizes them into a single type.

To what extent is the custom error normalized into an `Error`? Even if limited to debugging purposes, there might be properties of the custom error that might be useful for tracking back the reason of the unexpected behavior. 

Talking more specifically about my particular case, I am using JavaScript generators to simulate do notation, and the `Free` monad to control effects. I was considering using exceptions within the generators as a familiar way to signal erroneous, yet contemplated situations, such as:

```javascript
const identity = yield getIdentity(token); // getIdentity = Free.lift(GetIdentity)
if (!isAdmin(identity)) {
    throw new NotAllowed();
}
```

The `Free` monad would later be interpreted to `Future`.

My impression is that introducing `Either`s would clutter the business logic, since it would require interleaving folding with additional `yield` / `yield*` and generator functions. In light of your explanation, I guess that the design of `Future` is not (rightfully) meant to support my attempt.

Thank you!

**Comment by Avaq** [comment]
> Even if limited to debugging purposes, there might be properties of the custom error that might be useful for tracking back the reason of the unexpected behaviour.

The original caught value is exposed as one of the properties of the Error. See https://github.com/fluture-js/Fluture#debugging. Again, I advice against using exceptions for control flow. Once the exception makes it into the crash branch of a Future, it should be considered an invalid program state.

> I was considering using exceptions within the generators as a familiar way to signal erroneous, yet contemplated situations

You can, but the interpreter of your coroutine would need to catch the exceptions, and they shouldn't propagate outwards and be caught by Fluture.

**Comment by iliocatallo** [comment]
Hi,

Sorry for getting back so late to this.

> The original caught value is exposed as one of the properties of the Error. See https://github.com/fluture-js/Fluture#debugging. Again, I advice against using this branch for control flow. Once the exception makes it into the crash branch of a Future, it should be considered an invalid program state.

Thank you for the pointer.

> You can, but the interpreter of your coroutine would need to catch the exceptions, and they shouldn't propagate outwards and be caught by Fluture.

Agreed; I imagine that one such interpreter would either be written ad-hoc or require more parameterization than the natural transformation that provides the mapping between DSL terms and effects.

Anyway, I guess that the original doubt is solved – so I'm closing the issue.

Thank you!
