### ISSUE TITLE
Why not thenables?

### ISSUE THREAD

**Issue by FbN** [fluture-js/Fluture#448]
Why not adding a "then" method to convert into Promise to make a Fluture instance consumable by await? Could spare some line of code when integrating with other libs. 

this way:

const f = Future.resolve(1)
async function myApp() {
...
const r2 = await f
...
}

Instead of

const f = Future.resolve(1)
async function myApp() {
...
const r2 = await Future.promise(f)
...
}

That may be useful in an async function because we dont have to discriminate between futures and promises

**Comment by dicearr** [comment]
I am probably misunderstanding you but, a Future can be easily turned into a Promise by using [`Future.promise`](https://github.com/fluture-js/Fluture#promise).

**Comment by FbN** [comment]
Sure. What am I saying is that if we add a "then" method to a futureinstance that simply call Future.promise on itself we can write this way:

const f = Future.resolve(1)
async function myApp() {
   ... 
    const r2 = await f
   ... 
}

Instead of

const f = Future.resolve(1)
async function myApp() {
   ... 
    const r2 = await Future.promise(f)
   ... 
} 

That may be useful in an async function because we dont have to discriminate between futures and promises

**Comment by FbN** [comment]
I agree with you that it will be confusing for newcomers.

The idea comes to my mind building a lib to work with the DB that lazy return Fluture futures. My object implement a fork method, like Fluture operator.

But there is no a standard interface between Fluture (F.lock()()()), my lib (myobject.fork()()) and standard promises (promise.then()).

So I have to discriminate at consume time how to consume the 3 different kind of objects to mix results.

Reasoning about native async/await support, probably a .then method would be a nice interface to implement in any library that can be consumed as promises.

But as you suggest I can add it to Futures myself. So I'm ok with that solution for my project :)

**Comment by Avaq** [comment]
See also #35
