### ISSUE TITLE
Async Iterators

### ISSUE THREAD

**Issue by ftaiolivista** [fluture-js/Fluture#477]
I was trining to figure how to implement with Fluture an asyncronous iterator.

For example take this csv parsing code ([source](https://csv.js.org/parse/api/async_iterator/)):

```js
const assert = require('assert');
const generate = require('csv-generate');
const parse = require('csv-parse')

(async () => {
  // Initialise the parser by generating random records
  const parser = generate({
    high_water_mark: 64 * 64,
    length: 100
  }).pipe(
    parse()
  )
  // Intialise count
  let count = 0;
  // Report start
  process.stdout.write('start\n')
  // Iterate through each records
  for await (const record of parser) {
    // Report current line
    process.stdout.write(`${count++} ${record.join(',')}\n`)
    // Fake asynchronous operation
    await new Promise((resolve) => setTimeout(resolve, 100))
  }
  // Report end
  process.stdout.write('...done\n')
  // Validation
  assert.strictEqual(count, 100)
})()
```

How do you convert this to Fluture? I mean, I dont want to wrap all the code with an attempP but obtain a Future that parse single records to chain other elaboration to it

**Comment by Avaq** [comment]
Hi @ftaiolivista. I answered a very similar question some time ago. It was in a GitHub issue, so not that easy to discover. I converted it to a Q&A Discussion. I think it might be what you need: https://github.com/fluture-js/Fluture/discussions/478

**Comment by ftaiolivista** [comment]
Thank you @Avaq for the quick reply. Looked ad #478. Looks clear how to wrap a standard generator with Lazy List but not clear to me on how to wrap an async iterator that yield promises.

**Comment by Avaq** [comment]
Ah. I realize I've misunderstood your original question. I'm glad you've found a solution. I can't really see a way to work around the problem of that trailing Future: You _have_ to yield synchronously because Infinite only works with synchronous generators, and you only find out that the underlying async generator was done some ticks later, after having already yielded that Future.

**Comment by ftaiolivista** [comment]
Do you think could be possibile (and useful) to implement a method like 'go' in Fluture to work with async generator?
