### ISSUE TITLE
Implement #done(callback) - a counterpart to .node()

### ISSUE THREAD

**Issue by jmatsushita** [fluture-js/Fluture#79]
Hi there,

Just came accross Fluture and giving it a try to try and bring some functional tricks inside an existing node framework (seneca). 

In the way that there is `.node()` abiding by the NodeJS convention of `(err, results)` maybe there should be a version of `.fork()` which allows to consume the future by executing a node `callback(err, results)`? 

Maybe a `.done()` ?

Cheers!

Jun

**Comment by jmatsushita** [comment]
Basically just a thin wrapper:

```
function cb(err, result) { 
  // handed over to me from a framework
}

Future.of(1)
// .done(cb)
  .fork(err =>cb(err), res => cb(null, res))
```

**Comment by Avaq** [comment]
Seems like a good idea. I'll let it sink in, but feel free to open a PR in the mean time, if you wish!

**Comment by Avaq** [comment]
I'm going to include this feature in the `6.0` release. If you'd like to see it earlier (as `6.0` is probably at least a month away), feel free to submit a pull request to the `5.x` branch.

**Comment by Avaq** [comment]
This function appears to have been lost.
