### ISSUE TITLE
Multi arity .node()

### ISSUE THREAD

**Issue by jmatsushita** [fluture-js/Fluture#81]
Hi there,

I would find it useful to be able to call node style callback functions with one or several arguments.

For instance in the current example:
```
Future.node(done => fs.readFile('package.json', 'utf8', done))
```

Is a future with no arguments, but it would be useful to be able to wrap fs.readFile into a future of one or two arguments.

Cheers,

Jun

**Comment by jmatsushita** [comment]
Doing this works just fine:
```
FReadFile = (a, b) => Future.node(fs.readFile(a, b, done)
FReadFile('package.json', 'urf-8')
  .fork(console.log, console.log)
```

**Comment by Avaq** [comment]
There's also the [`futurize`](https://github.com/futurize/futurize) library, as described in [the futurziation section](https://github.com/fluture-js/Fluture#futurization) of the readme. Personally I prefer the solution you proposed though. :)
