### ISSUE TITLE
Threading state

### ISSUE THREAD

**Issue by jmatsushita** [fluture-js/Fluture#82]
I'm trying to manually thread some state through chained futures:

```
F.of({ state })
      .chain(({ state }) => F.of({ state, ...someFuture(state).value(x => x) }))
      .chain(({ state }) => F.of({ state, ...someOtherFuture(state).value(x => x) })) 
      .fork(console.log, console.log);
```

My thought is that with this approach and someFuture() and someOtherFuture returning ```{ state: "new"}``` this would essentially replace the state as if a `put` was ran in a State monad.

The problem here is that clearly nested Futures are not supposed to work like this as I figure F.of() evaluates its argument strictly which returns the actual function object rather than the result of `.value()`.

Do you have thoughts on how to accomplish this kind of explicit state threading?

**Comment by jmatsushita** [comment]
I should precise that the idea is to actually pass pieces of state to `someFuture` to allow it to not have to know about the entirety of state, so more in fact something like:
```
F.of({ state })
      .chain(({ state }) => F.of({ state, moreState: someFuture(state).value(x => x) }))
      .chain(({ state, moreState }) => F.of({ state, moreState, evenMoreState: someOtherFuture(state).value(x => x) })) 
      .fork(console.log, console.log);
```

**Comment by Avaq** [comment]
For cases like this, `Future.do` actually flattens that code really nicely.

**Comment by jmatsushita** [comment]
Ah very nice! So it looks like there are at least 3 different implementations of do in fantasy land (https://github.com/jwoudenberg/fantasy-do https://github.com/Risto-Stevcev/do-notation https://github.com/russellmcc/fantasydo), which with Flutures' makes 4. 

Any hope for a do that works with all monads? How about one that would also work with https://github.com/mattbierner/akh ?

**Comment by Avaq** [comment]
Most `do` implementations fail when a Future is forked twice, because of stateful generators. I thought of a `do` which fixes that, but it has other problems associated with Functors of multiple values (like Array). :(

**Comment by jmatsushita** [comment]
Ugh. Sounds hard :)

Am I right that you can't pass an argument to the Iterator? It'd be quite useful to compose chain and do in sequence...

Maybe:
```
.do1 :: ((a) -> Iterator) -> Future a b
.do2 :: ((a,b) -> Iterator) -> Future a b
```

**Comment by jmatsushita** [comment]
ah well a workaround is just to wrap the do in a function which takes an argument and use the closure. i.e. this works!
```
F.of( {state} )
  .chain({ state}) => F.do(function*() {
    const moreState = yield someFuture(state);
    const evenMoreState = yield someOtherFuture(state)
    return ({ state, moreState, evenMoreState })
  .fork(console.log, console.log)
```

PS: this should use the attempt combinator as described in the README.md

**Comment by jmatsushita** [comment]
Humm.... There's more boilerplate than I had hoped when I try to use `attempt` and pass `moreState` to `someOtherFuture()` because of the Either Future interleaving:
```
const attempt = F.fold(S.Left, S.Right);

F.of( {state} )
  .chain(({ state }) => F.do(function*() {
    const moreState = yield attempt(someFuture(state));
    const evenMoreState = yield S.traverse(FutureType, someOtherFuture, moreState)
    const res = S.traverse(Array, x => x, [ some, other ])
    return S.either(
      left => `Oh no! ${left}`,
      ([ some, other]) => ({ state, some, other }),
      res
    )
   }))
  .fork(console.log, console.log)
```

Any suggestion on how to clean that up? Could I use pipeK in the spirit of https://github.com/sanctuary-js/sanctuary/issues/53 ? Or more likely use monad transformers like https://github.com/mattbierner/akh ( I guess that would require a FutureT which is probably even harder than `.do` ?) ?

**Comment by jmatsushita** [comment]
Well it looks like with some higher order functions and reverting to chain as the effect sequencing syntax (instead of yields) I was able to tuck away some of the boilerplate and make things much more readable:

```
const thread = (left, right, future) => function*(){ return S.either(left, right, yield F.fold(S.Left, S.Right, future))}

F.of( {state} )
      .chain(({ state }) => F.do(thread(left => `Oh no! ${left}`, some => ({ state, some }), someFuture(state))))
      .chain(({ state, some }) => F.do(thread(left => `Oh no! ${left}`, other => ({ state, some, other }), someOtherFuture(some))))
  .fork(console.log, console.log)
```

What do you think? 
```

**Comment by jmatsushita** [comment]
After some well needed confusion dissipation, I just realised that what I wanted to do was simply:
```
F.of({ state })
      .chain(({ state }) => someFuture(state).map(some => ({ state, some }))
      .chain(({ state, some }) => someOtherFuture(state).map(other => ({ state, some, other })) 
      .fork(console.log, console.log);
```

I was trying to play with Monads when in fact things were just a Functor instance away! Duh. :)

**Comment by NodeGuy** [comment]
I think what you're looking for is a [State Transformer](https://github.com/mattbierner/akh-state) on top of a Future.
