### ISSUE TITLE
Interoperable do

### ISSUE THREAD

**Issue by jmatsushita** [fluture-js/Fluture#83]
I thought I'd open an issue to track progress on this and maybe bring in some fantasy-land veterans to advise. As pointed out by @Avaq in #82 

> Most do implementations fail when a Future is forked twice, because of stateful generators. I thought of a do which fixes that, but it has other problems associated with Functors of multiple values (like Array). :(

**Comment by Avaq** [comment]
References

* Issue in Freeky: https://github.com/DrBoolean/freeky/issues/4
* PR in Fluture: https://github.com/fluture-js/Fluture/pull/10
* Proposed solution: https://gist.github.com/Avaq/3128647d86abef4d1284d4de456ab829

**Comment by Avaq** [comment]
I'm closing this issue because it is not (yet) actionable. Feel free to keep referring people here to continue the discussion.
