### ISSUE TITLE
.thread() for Either / Future monad stacking

### ISSUE THREAD

**Issue by jmatsushita** [fluture-js/Fluture#84]
I think that the `thread` higher order function described in #82 

```
const thread = (left, right, future) => function*(){ return S.either(left, right, yield F.fold(S.Left, S.Right, future))}

F.of( {state} )
      .chain(({ state }) => F.do(thread(left => `Oh no! ${left}`, some => ({ state, some }), someFuture(state))))
      .chain(({ state, some }) => F.do(thread(left => `Oh no! ${left}`, other => ({ state, some, other }), someOtherFuture(some))))
  .fork(console.log, console.log)
```

defines some sort of mini monad transformer which allows to thread an Either Monad with the Fluture monad. And I guess this makes the code above some kind of Keisli composition for 2 monads? My theory doesn't hold up yet there...

I'm thinking that there's probably a well known interface/type class for this, maybe requiring monad transformers and lifting (as discussed in mattbierner/akh#31) ?

It could be a nice ad-hoc short term addition to have a `.thread()` operation in Fluture, but there's probably a more composable way?

**Comment by Avaq** [comment]
You can always switch to function composition over fluent style to mix in your own functions (see https://github.com/fluture-js/Fluture/issues/78#issuecomment-286698538).

On a side note: It strikes me as redundant to have a Future of an Either (outside the context of `Future.do`), because Future already encodes a superset of Either, that is, it has a left and right branch. I'm missing a concrete enough example to show the practical use.

**Comment by jmatsushita** [comment]
Oh I am quite confused :) I think that indeed it doesn't have anything to do with stacking Either. I think it has to do with being able to compose indeed. The practical case I'm trying to get working is the one in #82 where I want to be able to thread state and wrap the output of a Future in a Data type (in my example some kind of javascript object).

I'm really using the `right` function argument of `thread` to post-compose right and using do notation to be able to "open" the future and return the "wrapped" element (with right post applied to it). So thinking about it I guess I could just have used the `Functor` instance!

I'm also realising that with the `thread` function above I'm actually breaking error handling because folding (because of the `.do`) and `S.either` will never `reject`. 

Ugh... :)
