### ISSUE TITLE
Implement Alternative using race/never

### ISSUE THREAD

**Issue by Avaq** [fluture-js/Fluture#89]
Now that `race` has a special case for `Never` instances, we can implement lawful Alternative using `race` and `never`. This would mean that conversion to the `ConcurrentFuture` would *only* be necessary to get parallel `ap` behavior.

**Comment by safareli** [comment]
https://github.com/fluture-js/concurrify/issues/3#issuecomment-295275924

**Comment by Avaq** [comment]
These ideas originated in a conversation with you on Gitter:

> I've been lead to another question by reading the (beautiful) source-code of [Creed](https://github.com/briancavalier/creed). Creed implements chain-derived (sequential) `ap` *and* parallel `alt` on the same type. Why did we consider this impossible again?
> -- @avaq

> there is no "clear" answer to that, technically you could do it and it will be lawful
briancavalier/creed#92
fantasyland/fantasy-land#203
> but Monadic structure could be MonadPlus (or MonadOr or MonadZero) and i didn't went there farther because there is still debate on it so if it's finalised and we decide to "port" it to FL then such alternative instance could be invalid if structure is also made MonadPlus...
> -- @safareli 

> Ah. So even in Haskell they're not so sure. o.o
> Because in that case I could've implemented concurrify as merely Apply, and extend it as such:
> ```js
> const ConcurrentFuture = concurrify(Future, myParalellAp);
> ConcurrentFuture[FL.of] = function(x){ return ConcurrentFuture(Future[FL.of](x)) }
> ConcurrentFuture[FL.zero] = function(){ return ConcurrentFuture(Future[FL.zero]()) }
> ConcurrentFuture.prototype[FL.alt] = function(b){ return this[FL.alt](b) }
> ```
> -- @avaq

----

It seems that at the time, you were unsure if Monad with Alternative is lawful. It seems that @briancavalier has chosen for the more convenient approach of having both instances on his structure in briancavalier/creed#92. If no new insights have come to light in the mean time, I would be inclined to proceed with this idea. Since it seems to be a polarizing subjects, though, I will not push this for the `6.0` release. I'm also curious to learn whether Brian Cavalier's ideas about this are still the same (hence the ping).

**Comment by briancavalier** [comment]
> I've been lead to another question by reading the (beautiful) source-code of Creed

Thank you, @Avaq!

> the more convenient approach of having both instances

So far, yeah, it's proven to be convenient and not confusing.  My plan was to see how it played out in 1.x and then change it if necessary in 2.0.  There are some subtle differences, like promises not being lazy.  So, in a left catch `p1.alt(p2)`, the work of p1 and p2 would already be in progress (or inevitably will be soon).  In many cases, though, you'd probably rather defer the work of p2 by providing a function instead of another promise, at which point you'd probably rather use `p1.catch`.  That was one of a few things that nudged me toward `never`+`race`.

Cheers!

**Comment by Avaq** [comment]
> There are some subtle differences, like promises not being lazy

Oh, hold on! I never thought about that in the context of "algebraic semantics". This fact means that intrinsically, Promises behave concurrently. So `Creed#ap` may be implemented in terms of `chain`, but since `ap` takes `Promise` (as opposed to `a -> Promise`), it's already running. With that in mind, `never`+`race` makes a lot of sense for Promises, because any given pair of Promises is automatically in a "race".

It also might mean that `Creed#ap` is in somewhat of a gray area when it comes to being lawful in the context of Monad. Is the fact that Promises are eager considered "concurrent" behavior?

All of this gives me a new perspective on the matter. Thanks! :)

I'll let it sink in and think it over once more, whether Future should stay away from `never`+`race` as the basis for Alternative simply because Futures have the *ability* not to race.

**Comment by safareli** [comment]
@Avaq great insights ⛱  (I thought creed was like other lazy promises)

**Comment by Avaq** [comment]
I'm going to close this issue while I ponder. I think at this stage it's unlikely that I will proceed.

**Comment by Avaq** [comment]
In light of #290 and [Gitter](https://gitter.im/fluture-js/Fluture?at=5bfdc9cdd24f9324d2632e91), I've reopened this issue.

**Comment by Avaq** [comment]
By refreshing my memory and going over it in Gitter, I quickly realized that parallel `alt` behaviour in Monads is at best frowned upon, and at worst breaking monadic laws.

The only option for a monadic Future is to implement `alt` without `zero` using "or semantics".
