### ISSUE TITLE
Issue traversing with Futures

### ISSUE THREAD

**Issue by jtormey** [fluture-js/Fluture#94]
I'm trying to create a traversal of Futures, but have been running into some unexpected issues. For example, with sanctuary:

```
// S.traverse :: (Applicative f, Traversable t) => TypeRep f -⁠> (a -⁠> f b) -⁠> t a -⁠> f (t b)
S.traverse(Future, (x) => Future.after(100, x), [1, 2])
```

I would expect this to return `Future([1, 2])`. However, traverse throws a type constraint violation error:

```
TypeError: Type-variable constraint violation

traverse :: (Applicative f, Traversable t) => TypeRep f -> (a -> f b) -> t a -> f (t b)
                                                                 ^^^
                                                                  1

1)  Future.after(100, 1) ::

Since there is no type of which all the above values are members, the type-variable constraint has been violated.
```

Ramda also seems to have issues traversing:

```
// R.traverse :: (Applicative f, Traversable t) => (a -> f a) -> (a -> f b) -> t a -> f (t b)
R.traverse(Future.of, (x) => Future.after(100, x), [1, 2])
```

This will throw:

```
TypeError: Future#ap expects its first argument to be a Future of a Function
  Actual: Future.of([])
```

Any idea of what's happening here? Could be that I'm missing something obvious, but the same approach works when using Either, Maybe, or Task.

Thanks!

**Comment by davidchambers** [comment]
See <https://github.com/fluture-js/Fluture#sanctuary> for the solution to this problem. :)

**Comment by jtormey** [comment]
Ah, the README, of course haha. Works great now, thanks for pointing me in the right direction!

**Comment by hojberg** [comment]
What's the solution to `R.traverse`?

**Comment by Avaq** [comment]
This issue should only occur when using an outdated version of *both* Ramda and Fluture.
